# Practice Numpy with some exercises


Hello! After reading for the last two days about numpy, i wanna start taking some exercises to test my knowledge. I wanna mention that the exercises ideas are from this repo: [link](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb). I am not the author of this exercises, they are under MIT License, as for  my repo i just post how i would solve this mini challenges for sake of  learning is, so hopefully it doesn t create any problems. If you have any issue with this notebook/content or violate any rights, please let me know asap in order to solve the problem, So let's get started.

1. Importing numpy as np

In [1]:
import numpy as np

2. Print numpy version 

In [3]:
np.version.version

'2.2.3'

3. Create a null vector of size 10

In [15]:
a = np.zeros(10,dtype='int32')
print(a)

[0 0 0 0 0 0 0 0 0 0]


4. How to find the memory size of any array:

In [21]:
print(a.size)
print(a.itemsize)
print(a.size*a.itemsize)

#or

print(a.nbytes)

10
4
40
40


5. How to get the documentation of the numpy add function from the command line?

In [ ]:
np.add?

6. Create a null vector of size10 but the fifth element is one

In [25]:
b=np.zeros(10,dtype='int32')
b[4]=1
print(b)

[0 0 0 0 1 0 0 0 0 0]


7. Create a vector with values ranging from 10 to 49

In [27]:
c=np.array([i for i in range(10,50)])
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector(first element become last)

In [29]:
d = np.flip(c)
print(d)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 

In [53]:
e = np.array([i for i in range(9)])
f= e.reshape((3,3))
print(f)

#or

f = np.arange(0,9).reshape(3,3)
print(f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


10.Find the indices of non-zero elements from [1,2,0,0,4,0]

In [44]:
f = np.array([1,2,0,0,4,0])

for i in range(len(f)):
    if(f[i]!=0):
        print(i)


0
1
4


11. Create a 3x3 identity matrix

In [55]:
x = np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values: 

In [47]:
e = np.random.random(size=(3,3,3))
print(e)

[[[0.21392917 0.06389445 0.40447715]
  [0.28250588 0.86484216 0.76893007]
  [0.39260812 0.15874137 0.59586446]]

 [[0.58321626 0.62895712 0.59386766]
  [0.29527341 0.92740136 0.89961174]
  [0.46785054 0.93955176 0.11024927]]

 [[0.11221489 0.85688832 0.15428878]
  [0.04783839 0.74059581 0.11017024]
  [0.08114149 0.02869036 0.79399797]]]


13. Create a 10x10 array with random values and find the minimum and maximum values

In [61]:
y = np.random.random((10,10))
print(y.min())
print(y.max())

0.0182803393603852
0.9973334845652128


14. Create a random vector of size 30 and find the mean value

In [62]:
z= np.random.random(30)
print(z.mean())

0.45436704834511443


15. Create a 2d array with 1 on the border and 0 inside

In [64]:
t = np.ones((5,5))
t[1:-1,1:-1]=np.zeros((3,3))

print(t)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border filled with zeros around an existing array:

In [81]:
r = np.random.random(10)
r= np.vstack([np.zeros(10),r,np.zeros(10)])
r = np.hstack([np.zeros(3).reshape((3,1)),r,np.zeros(3).reshape((3,1))])


print(r)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.54488434 0.23352371 0.26945355 0.99332742 0.53459122
  0.50373234 0.40327572 0.76431287 0.31512546 0.80605369 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]]


18. Create a 5x5 matrix with values 1,2,3,4 below diagonal 

In [100]:
v= np.array([i for i in range(25)])
v = v.reshape((5,5))

print(v)

v[[1,2,3,4],[0,1,2,3]] = [1,2,3,4]

print(v)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 1  6  7  8  9]
 [10  2 12 13 14]
 [15 16  3 18 19]
 [20 21 22  4 24]]


19. Create a 8x8 matrix and fill it with checkerboard pattern

In [113]:
u = np.zeros(64).reshape((8,8))

u[0::2,0::2]=1
u[1::2,1::2]=1

print(u)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [ ]:
u = np.zeros(336).reshape((6,7,8)) # coloane linii nr matrici
u[2][3][3] = 100

print(u)
print(u[2][3][3])

21. Create a checkerboard 8x8 matrix using the tile function 

In [157]:
p1 = np.array([[1, 0], [0, 1]])
 
np.tile(p1,(4,4))


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

22. Normalize a matrix: 

In [161]:
b = np.random.randint(8,size=(5,5))
max_b = b.max()
min_b = b.min()

print((b-min_b)/(max_b-min_b))

[[0.28571429 0.85714286 0.85714286 0.71428571 0.57142857]
 [0.85714286 0.28571429 0.71428571 0.71428571 1.        ]
 [0.57142857 0.57142857 0.42857143 0.         0.42857143]
 [0.85714286 1.         0.57142857 0.         0.71428571]
 [0.28571429 1.         0.28571429 0.57142857 0.28571429]]


In [166]:
a = [1,2,3,4,5,6,1,2,3,4,5,6]
b=np.array(list(set(a)))
print(b)

[1 2 3 4 5 6]


In [ ]:
dasdadasasdadaddada

str.find
str.rfind