# First Time trying Jupyter Notebook - Introduction into Numpy


Today, I am exploring the NumPy Tutorial provided by freeCodeCamp on their official YouTube channel. You can find the original video here: NumPy Course - Complete Python NumPy Tutorial.  [link](https://www.youtube.com/watch?v=QUT1VHiLmmI&t=186s) and the original repo [here](https://github.com/KeithGalli/NumPy)

I want to emphasize that I am not the author of any of the information presented below. This notebook is purely for learning and practicing variations from what's presented in the video, and I have included the video link to properly credit the original creators.

If there are any concerns regarding the use of this reference, please let me know. I deeply appreciate the educational content provided by freeCodeCamp.

Now, let's get started! 🚀

In [1]:
print("hello world")

hello world


I just printed a statement to get accoustemed to the jupyter workflow and i just finished setting up my first project with .venv yey 

Now i am going to record a few notes out of the video just to remember important aspects


## Introductory things: 

>Remember to "pip install numpy" 


### Informations about numpy why does it works: 

- Numpy is faster than lists
- Is it so, cause Numpy have a smaller representation in binary code: 

- Numpy use continous memory location. 


In [1]:

import numpy as np

### The Basics

In [80]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [81]:
b=np.array([1.5,2.4,5.6])
print(b)

[1.5 2.4 5.6]


In [82]:
#CREATE A MATRIX
c= np.array([[1.5,2.4,5.6],[1.5,2.4,5.6]])
print(c)

[[1.5 2.4 5.6]
 [1.5 2.4 5.6]]


In [83]:
#Getting the dimension of numpy arrays - the number of lines or columns

print(a.ndim)
print(c.ndim)

1
2


In [84]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(3,)
(2, 3)


In [85]:
#clasic way to get the type - but not correct 
# print(type(a))
# print(type(c))

# getting type + itemsize  + number of elements(size) + total size
print(a.dtype)
print(a.itemsize)
print(a.size)
print(f"total size of array a is:{a.itemsize * a.size}")

int64
8
3
total size of array a is:24


### Accesing/Changing specific elements, rows,columns, etc 

In [44]:
d = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [47]:
#Getting a specific element: 

print(d[1,5])

13


In [61]:
# Getting a specific row:
print(d[0, :])


[1 2 3 4 5 6 7]


In [64]:
#Getting a specific column:
print(d[:,3])

[ 4 11]


In [ ]:
#Getting a specific pattern array [start:end:stepsize]

print(d[0,1:6:2])

[2 4 6]


### Initializing different types of arrays 

In [ ]:
#All items are zeros
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ALL ITEMS ARE ONES
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [77]:
a = np.full((2,2),100)
print(a)

[[100 100]
 [100 100]]


In [90]:
# Any other number(full_like)
a=np.full_like(c, 44)
#or
a=np.full(a.shape,44)
print(a)

[[44 44 44]
 [44 44 44]]


In [103]:
#random numbers:
# a= np.random.rand(4,3,2)
# print(a)

# daca vreau sa aiba forma , adica formatul de colaone lini ale altei variabile atunci fac asa

a=np.random.random_sample(c.shape)
print(a)

[[0.61756824 0.09984856 0.71183886]
 [0.94268457 0.44452728 0.10053457]]


In [130]:
#Random integer matrix: 
np.random.randint(7,size=(3,3))

array([[2, 6, 2],
       [1, 0, 0],
       [6, 0, 6]], dtype=int32)

In [132]:
#Identityt MAtrix -amtrice diagonala
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# create a matrix with 3 concentric sqaures, one with ones, one with 0 and one with 9

# output = np.ones((5,5))
# output[1:4,1:4]=np.zeros((3,3))
# output[2,2]=9
# print(output)

name = input("Enter your name: ")
print("Hello,", name)
