# Day 5 of Learning Python - Numpy Journey continue

- Yesterday i learned about the basics of numpy, how to declare them, how to acces elements from it, how to slice it in various ways, and for today i am going to continue the video from freecodecamp about numpy in order to learn new things about numpy. ([youtube link](https://www.youtube.com/watch?v=QUT1VHiLmmI&t=2137s)) | [official_github_link](https://github.com/KeithGalli/NumPy). 

- Again, I want to emphasize that I am not the author of any of the theoretical information presented below. This notebook is purely for learning and practicing variations from what's presented in the video, and I have included the video link to properly credit the original creators.

- If there are any concerns regarding the use of this reference, please let me know. I deeply appreciate the educational content provided by freeCodeCamp.

- Now let's get the day started

## Continuing the section from yesterday

In [2]:
import numpy as np

In [ ]:
#the solution for the last exercise from yesterday
a=np.ones((5,5))
b=np.zeros((3,3))
b[1,1]=9
a[1:4,1:4]=b.copy()

print(a)
#!!!!! SHALLOW VS DEEP COPY 

# Deep copy
b=a.copy()
print(b)

#Shallow copy - if i modify 1 element in b, the a is afected as well cause they share the same memory zone
b=a
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])


print(a+b)
print(a-b)
print(a*b)
print(a%b)
print(b/a)
print(b//a)
print(a**2)



[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[1 2 3 4]
[5.         3.         2.33333333 2.        ]
[5 3 2 2]


In [24]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Linear Algebra

In [34]:
#Multiplying of two matrices
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [35]:
#GEtting the determinant
c=np.identity(3)

print(np.linalg.det(c))

1.0


## Statistics

In [50]:
stats = np.array([[1,5,8],[5,6,7]])
stats

array([[1, 5, 8],
       [5, 6, 7]])

In [ ]:
# ! if i want the column or line with the biggest numbers , i should use axis in the stats unction 1=line;0=column!!!!!!!
print(np.min(stats))

1


In [59]:
print(np.max(stats,axis=1))
print(np.max(stats,axis=0))

[8 7]
[5 6 8]


In [40]:
print(np.mean(stats))

4.0


In [42]:
print(np.median(stats))

4.0


## Reorganizing Arrays

In [73]:
a=np.full((3,4),1)

b=np.zeros((3,4))

print(a)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [80]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

stack = np.vstack([v1,v2])
stack2 = np.hstack([v1,v2])

print(stack)
print(stack2)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


## Learning extra things

In [118]:
#Getting data from a file lke txt
text = np.genfromtxt('random_numbers.txt',delimiter=',')

text= text.astype('int32')
print(text)

[[40 69 16 89 64 68 36 24 14 90]
 [38  6  9 54 16  5 55 86 84 61]
 [89 18 31 69 74 13 92 23 93 98]]


In [120]:
#poti verifica daca ai anumite valori si sa faci o matrice de true false
text = (text > 10) & (text <60)
print(text)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


In [ ]:
#exercitiu practic:

matrix1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(matrix1)
#or

line1=np.array([1,2,3,4,5])
line2=np.array([6,7,8,9,10])
line3=np.array([11,12,13,14,15])
line4=np.array([16,17,18,19,20])
line5=np.array([21,22,23,24,25])
line6=np.array([26,27,28,29,30])
matrix2=np.vstack([line1,line2,line3,line4,line5,line6])

#ex1
# print(matrix1[2:4,0:2])


#ex2
# print(matrix1[[0,1,2,3],[1,2,3,4]])

#ex3
# print(matrix1[0,3:5])
# print(matrix1[4,3:5])
# print(matrix1[5,3:5])
# new_matrix=np.hstack([matrix1[0,3:5],matrix1[4,3:5],matrix1[5,3:5]])

# print(new_matrix)

print(matrix1[[0,4,5],3:5])


#!!! IF I WANNA TAKE AN ARRAY OF ELELMENT THAT ARE 1 PER LINE.COLUMN USE THE EX2, IF I WANT SPECIFIC LINES != NO COLUMNS THEN USE EX3 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 4  5]
 [24 25]
 [29 30]]
